### PR TITLE
Added my slogan closes 

### PR DESCRIPTION
**Pull request by mulraind001**
Add Slogan

### CODE REVIEW

**Comment by claesmk** [comment]
You can go ahead and merge this into your fork.  After that you can add your slogan and then submit a pull request into the NCATCOMP410 repo

**Comment by mulraind001** [comment]
I press the merge. how do i pull request into the repo?

**Comment by claesmk** [comment]
> I press the merge. how do i pull request into the repo?

First you need to push your code with your slogan in it to your [fork](https://github.com/mulraind001/comp410_summer_2022).  

After you do that, from your [fork](https://github.com/mulraind001/comp410_summer_2022) click on the Pull request tab then the New Pull Request button

**Comment by mulraind001** [comment]
It says i need a review now

**Pull request merged**
